### PR TITLE
Create conflict with #2

### PR DESCRIPTION
**Pull request by cubrr**
Merging either #2 or this will create a merge conflict in the other. Probably.

### CODE REVIEW

**Comment by ElectroCamel** [comment]
Yeah, it should. Have you added final just to create a conflict, right?

**Comment by cubrr** [comment]
> Have you added final just to create a conflict, right?

Yes! I would imagine that the spaces removed from the end of the lines by my editor (or git?) would suffice though. Let me change that.

**Comment by cubrr** [comment]
Woo! Merge conflicts!

**Comment by HappyZombies** [comment]
Alright, let me go ahead and merge this..

**Comment by cubrr** [comment]
I don't think we need this anymore :)

**Pull request closed without merging**
