### PR TITLE
Fixed three errors

### PR DESCRIPTION
**Pull request by ElectroCamel**
Error 1: Circle.java: line 8: typo: "ass" instead of "class" (I see what
you did there..)
Error 2: Circle.java: line 40: typo: "MaNy" instead of "many"
Error 3: Run_Circle: line 9: missing "new"

Also added a comment

### CODE REVIEW

**Comment by cubrr** [comment]
Missed [_"LOt"_ right next to _"MaNy"_](https://github.com/HappyZombies/Circle/pull/4/files#diff-d9959016630e43859175730149cd56acR41) :smile::

    // it's okay to call them r & c, but when you have A LOt of variables, r & c could 
    //                                                    ^

**Comment by ElectroCamel** [comment]
Lol. It's been a long day.

**Comment by HappyZombies** [comment]
Ah yes... But I didn't count my horrible typing as one of the three errors. There is actually one more error that no one has mentioned yet.

**Comment by ElectroCamel** [comment]
Oh, if I commit after I already sent a pull request it gets automatically added in the request. Good to know.

**Comment by cubrr** [comment]
> Oh, if I commit after I already sent a pull request it gets automatically added in the request. Good to know.

Yup! Remember to create a new branch if you start working on a new feature so that your pull request for a small bugfix doesn't turn into a pull request for a new feature!

**Comment by ElectroCamel** [comment]
Committed. I had already noticed that, but shrugged it off because I thought it was the same. Worked too much on PHP lately haha

**Pull request merged**
