### PR TITLE
Added Cylinder class

### PR DESCRIPTION
**Pull request by ElectroCamel**
Sorry for eventual errors (didn't try to compile)  and not-so-thorough comments. After 8 hours of coding, my brain is starting to pledge for sleep.

### CODE REVIEW

**Comment by Raijuu** [comment]
The Cylinder Class will solve world hunger.

**Comment by ElectroCamel** [comment]
It was made to provide an example of eridetariety. Since he is learning, I thought it'd be appreciated.

**Comment by Raijuu** [comment]
I was just seeing if I could comment on other people's pull requests!

**Pull request merged**
