### PR TITLE
Made a few changes

### PR DESCRIPTION
**Pull request by ChristaCode**
Practicing pull request.

Code is all compiling.

### CODE REVIEW

**Comment by HappyZombies** [comment]
Wow, very nice, can't wait to compile this and see what it can do. Now I wish I was just as smart so I could do stuff like this :((

**Comment by ChristaCode** [comment]
It's no more complicated than what you already had :)

**Comment by HappyZombies** [comment]
It's just for the past months, all the programming I have done involved the console command. I would like to, take it up a notch and make it nice and GUI like. Ya know. I'll be sure to read through yours more carefully so I can understand :)

**Comment by ChristaCode** [comment]
Here is where I got the code to draw the circle -
http://php.scripts.psu.edu/djh300/cmpsc221/notes-graphics-intro.php. I
cited it at the top of the Draw_Circle class.

Great tutorial, hope it helps!

**Pull request merged**
